### PR TITLE
#58 Speed Mode Timer Display

### LINKED ISSUE #58: Speed Mode - Timer Display
### Description

We want to show the current runs time, the last runs time, and then the historical fastest run. 

### Acceptance Criteria

Takes in the current run time, the last run time and the fastest run time,
looks like mock

### Proposed Solution

^
epic #56 

### Mocks

Screenshot 2024-01-24 at 11 34 22 PM

### PR DESCRIPTION
**Pull request by mliam0608**
Created a RunInfo component to keep track of an individual run and created TimerDisplay to display a grid of runs.

image

Closes #58

### CODE REVIEW

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
changes requested in slack

**Comment by mliam0608** [comment]
image
Updated screenshot

**Comment by mliam0608** [comment]
image
Updated screenshot

**Review by Peyton-McKee — APPROVED** [review]
theres some things we can change later but this looks good

**Pull request merged**
